[package]
name = "perfect_cursors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-time = "1"

[dev-dependencies]
eframe = "0.26.2"